version: "3.7"

services:
  quiz-app:
    image: node:12-alpine
    restart: always
    command: sh -c "npm install && npm run dev"
    ports:
      - 8000:8000
    working_dir: /usr/quiz-app
    volumes:
      - ./:/quiz-app
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin
      ME_CONFIG_MONGODB_URL: mongodb://root:admin@mongo:27017/quiz-app
  
  mongo-container:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: admin
    volumes:
      - quiz-app-mongo-data:/var/lib/mongo

volumes:
  quiz-app-mongo-data:
  

# ========================
# if using mysql
# ========================
  # environment:
    #   MYSQL_HOST: mysql
    #   MYSQL_USER: root
    #   MYSQL_PASSWORD: secret
    #   MYSQL_DB: quiz-app
#   mysql:
#     image: mysql:5.7
#     volumes:
#       - quiz-app-mysql-data:/var/lib/mysql
#     environment:
#       MYSQL_ROOT_PASSWORD: secret
#       MYSQL_DATABASE: quiz-app

# volumes:
#   quiz-app-mysql-data: