# fly.toml app configuration file generated for node-react-quiz-app-morning-forest-5197 on 2023-11-16T15:27:39+05:30
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "node-react-quiz-app"
primary_region = "arn"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
